### ISSUE TITLE
Missing SFC_SET_SCALE_INT_FLOAT_WRITE

### ISSUE THREAD

**Issue by sveinse** [roebel/pysndfile#2]
The libsndfile setting SFC_SET_SCALE_INT_FLOAT_WRITE is missing from the exposed pysndfile API. I've added a pull request for the change. I hope this can be taken into consideration. I am willing to waive copyright on this change if this is required.

https://github.com/roebel/pysndfile/pull/1

**Comment by roebel** [comment]
Hello, thanks for the bug report - I have a few other small bugs I would like to correct and will
 fix the missing command in the same update. I would prefer to avoid copyright problems for our internal use of the package, and so I would like to make use of your offer to waive your copyright on the bug fix.If you don't mind I would mention your contribution in the ChangeLog of the next release which would then be 1.3.3.

**Comment by sveinse** [comment]
Thank you, sounds very good. When do you expect 1.3.3 will be released? No commitment needed, just curious.

**Comment by roebel** [comment]
With a little bit of luck over the weekend.

**Comment by roebel** [comment]
Should be fine now. Please let me know if you still have a problem.

**Comment by sveinse** [comment]
Hi, just verified the new 1.3.3 release and it completes the test suite successfully, closing the issue. Thank you very much for a prompt fix. Merci beaucoup.
