### ISSUE TITLE
Remove cython from requirements.txt

### ISSUE THREAD

**Issue by sveinse** [roebel/pysndfile#5]
When installing pysndfile from a binary wheel, it will install `cython` as a dependency. I believe that the pysndfile doesn't require `cython` when not building the application.

I believe `cython` should be removed from `requirements.txt` as cython isn't required for running the application. The build dependencies are covered in the new `pyproject.toml`. I've tested this and it works fine.

**Comment by roebel** [comment]
Yes good observation, i changed this in the repos.

**Comment by sveinse** [comment]
Fixed in 1.3.7, closing issue
