### ISSUE TITLE
UserWarning: PySoundFile failed. Trying audioread instead.

### ISSUE THREAD

**Issue by ghost** [roebel/pysndfile#6]
I use an AWS sagemaker ml.t2.medium machine.
This is the distributaion:

`Linux ip-172-16-23-13 4.14.171-105.231.amzn1.x86_64 #1 SMP Thu Feb 27 23:49:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`  

I downloaded `libsndfile` with:
```
sudo wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz
tar -xzf libsndfile-1.0.28.tar.gz
```
And installed with:
```
cd libsndfile-1.0.28
./configure --prefix=/usr --disable-static --docdir=/usr/share/doc/libsndfile-1.0.28 && make
sudo make install
```
Then, I downloaded `pysndfile` with:
```
pip install pysoundfile
```
Now, everything is working great when trying to read a `.wav` file with `librosa`.  
But when I am trying to read a `.flac` file, it is writing:  
```
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/librosa/core/audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
```
It is working with `audioread`, but I think the `pysndfile` should work either.  
`libsndfile` does support `.flac` format.  
What can be the cause of this?  
Maybe my installation is not enough and I need to install the codec for `.flac`  in `libsndfile` somehow?  

Thank you,

**Comment by roebel** [comment]
Hello

you installed pysoundfile which is different from pysndfile.
See the docs here https://pysoundfile.readthedocs.io/en/latest/#installation

So you should raise your issue there.

Looking into your libsndfile install command it seems to me that you did not install dpendencies for flac and vorbis support.
