### ISSUE TITLE
cannot install from pip or source

### ISSUE THREAD

**Issue by saveriogzz** [roebel/pysndfile#7]
Hi!
I'm trying to install the package on a Linux machine but I cannot do it neither from pip nor from source.
I keep receiving the error 
```bash
[...]
 cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from _pysndfile.cpp:674:
  pysndfile.hh:56:10: fatal error: sndfile.h: No such file or directory
     56 | #include <sndfile.h>
        |          ^~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pysndfile
Failed to build pysndfile
ERROR: Could not build wheels for pysndfile which use PEP 517 and cannot be installed directly
```

do you have any clue how to solve this? Needless to say that I've updated setuptools, wheel and pip.

**Comment by roebel** [comment]
Hello 

> pysndfile.hh:56:10: fatal error: sndfile.h: No such file or directory
pysndfile is a wrapper for libsndfile. So you need to have libsndfile installed on your system and you make sure that 
the configuration used by setup.py find include and link files. You can have a look into setup.cfg where there are two lines commented out that allow to specify you install the PATHs 

Best

**Comment by roebel** [comment]
BTW, this is explained under compiling from sources in the README.md. ;-)
